name: nutrismart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_admin.png
    - assets/Images/register_admin.png
    - assets/images/org1.png
    - assets/images/org2.png
    - assets/images/org3.png
    - assets/images/org5.png
    - assets/images/sekolah1.png
    - assets/images/sekolah2.png
    - assets/images/sekolah3.png
    - assets/images/sekolah4.png


  fonts:
    - family: Sansita_Swashed
      fonts:
        - asset: assets/fonts/SansitaSwashed-VariableFont_wght.ttf
