name: nutrismart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_admin.png
    - assets/Images/register_admin.png

  fonts:
    - family: Sansita_Swashed
      fonts:
        - asset: assets/fonts/SansitaSwashed-VariableFont_wght.ttf
